from pyquery import PyQuery as pq

cookies_str = "optimizelyEndUserId=oeu1532569713196r0.5975193584464786; optimizelyBuckets=%7B%7D; _omappvp=t5KWuZJmchi5h9UStyGxdHqWeZm7zoDxtj025iSFkbr15f9vksRxNFoAoqpIoW2NmbGtAYKhz0hNTMXNvfFDa9woAq4B3z7n; RETURNING_VISITOR=true; _ga=GA1.2.486250441.1532569759; mp_dd81b79ad7bab9bd2b685a3a0116b034_mixpanel=%7B%22distinct_id%22%3A%20%2216589c52526184-0b8d9341b66dbc-39614807-1fa400-16589c52527a9b%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; dzuuid=4b969672-a28e-42b3-98ce-a3f5af0e8d4d; optimizelySegments=%7B%221595101009%22%3A%22search%22%2C%221596781023%22%3A%22gc%22%2C%221600230999%22%3A%22false%22%7D; om-yxqxn52jp9zs07u4yiiz=1542331371387; om-v2ztbriq3nusgrkbecgs=1542935065090; om-swx8od5qaum1mtdbq7qe=1543195953567; om-opcsulqohj0tavq2h6jz=1543886759910; om-usqx9tg38wzb4ryhav4e=1544146221698; _gid=GA1.2.818963861.1544419202; om-qwze5lkdfy9n0i0ot95z=1544419212326; om-eyoq6nv3nk6ofwa3rhzz=1544506362734; om-ptk1txj64xvw4x4u9hug=1544664416098; omGlobalInteractionCookie=1544664416098; JSESSIONID=B538BB9E5D53295F16C16C5B42BC399E; TH_CSRF=3847428072419124801; SPRING_SECURITY_REMEMBER_ME_COOKIE=U3RzVEhDK0tWcGtTMmtWMGlHNU5sQT09OmFVNmM2bndyc01WQm5DSUFZNVVwL3c9PQ; AWSELB=2B23F73512874A984846CB61011FAE4304C7C410AC6D2BD8DA2DA380073EAD554E22B9735186545710CBA36F8982913695204F268C6CA1DCA47DC66D55D9FAB03E146CDB7B; SESSION_STARTED=true; _parsely_session={%22sid%22:66%2C%22surl%22:%22https://dzone.com/%22%2C%22sref%22:%22%22%2C%22sts%22:1544706726907%2C%22slts%22:1544664405949}; _parsely_visitor={%22id%22:%22d86d7bdb-a3f9-49d5-862c-120107c28d4c%22%2C%22session_count%22:66%2C%22last_session_ts%22:1544706726907}; __insp_wid=1999343779; __insp_nv=true; __insp_targlpu=aHR0cHM6Ly9kem9uZS5jb20v; __insp_targlpt=RFpvbmU6IFByb2dyYW1taW5nICYgRGV2T3BzIG5ld3MsIHR1dG9yaWFscyAmIHRvb2xz; __insp_norec_sess=true; mp_022d397c8f6bfc6c6b289f607d96fc84_mixpanel=%7B%22distinct_id%22%3A%20%22165a9739dc144e-02caad40b36c9c-39614807-1fa400-165a9739dc24cc%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24search_engine%22%3A%20%22google%22%7D; __insp_slim=1544706794125; _gali=ng-app"
cookies = dict({key.strip(): val.strip() for key, val in [item.split("=") for item in cookies_str.split(";")]})

headers = {
    'User-Agent': "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 "
                  "Safari/537.36",
    "Host": "dzone.com",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6",
    "Accept-Encoding": "gzip, deflate, br",
    "DNT": "1",
    "Connection": "keep-alive",
}

import time

card_url_list = [
    "https://dzone.com/refcardz/cicd-with-containers",
    "https://dzone.com/refcardz/kubernetes-essentials",
    "https://dzone.com/refcardz/java-containerization",
    "https://dzone.com/refcardz/compliant-devops",
    "https://dzone.com/refcardz/intro-to-docker-monitoring",
    "https://dzone.com/refcardz/introduction-to-devsecops",
    "https://dzone.com/refcardz/understanding-stream-processing",
    "https://dzone.com/refcardz/messaging-infrastructure-for-iot-at-scale",
    "https://dzone.com/refcardz/test-design-automation",
    "https://dzone.com/refcardz/getting-started-with-kotlin",
    "https://dzone.com/refcardz/apache-kafka",
    "https://dzone.com/refcardz/graph-powered-search-neo4j-amp-elasticsearch",
    "https://dzone.com/refcardz/an-overview-of-graphql",
    "https://dzone.com/refcardz/getting-started-with-docker-1",
    "https://dzone.com/refcardz/getting-started-with-java-based-cms",
    "https://dzone.com/refcardz/reactive-microservices-with-lagom-and-java",
    "https://dzone.com/refcardz/getting-started-with-appium",
    "https://dzone.com/refcardz/preparing-continuous-delivery",
    "https://dzone.com/refcardz/net-on-linux",
    "https://dzone.com/refcardz/getting-started-with-hibernate",
    "https://dzone.com/refcardz/getting-started-with-microservices",
    "https://dzone.com/refcardz/cloud-foundry",
    "https://dzone.com/refcardz/querying-graphs-neo4j",
    "https://dzone.com/refcardz/rxjs-streams",
    "https://dzone.com/refcardz/reactjs-essentials",
    "https://dzone.com/refcardz/core-java",
    "https://dzone.com/refcardz/java-caching",
    "https://dzone.com/refcardz/essential-postgresql",
    "https://dzone.com/refcardz/csharp",
    "https://dzone.com/refcardz/regular-expressions",
    "https://dzone.com/refcardz/getting-started-phonegap",
    "https://dzone.com/refcardz/spring-batch-refcard",
    "https://dzone.com/refcardz/data-mining-discovering-and",
    "https://dzone.com/refcardz/html5-web-workers",
    "https://dzone.com/refcardz/core-json",
    "https://dzone.com/refcardz/refactoring-patterns",
    "https://dzone.com/refcardz/android-application",
    "https://dzone.com/refcardz/hbase",
    "https://dzone.com/refcardz/mockito",
    "https://dzone.com/refcardz/groovy",
    "https://dzone.com/refcardz/design-patterns",
    "https://dzone.com/refcardz/flex-mobile-development-build",
    "https://dzone.com/refcardz/spring-roo-open-source-rapid",
    "https://dzone.com/refcardz/webmatrix",
    "https://dzone.com/refcardz/mastering-portals-portlet",
    "https://dzone.com/refcardz/whats-new-jpa-20",
    "https://dzone.com/refcardz/html5-new-standards-web-interactivity",
    "https://dzone.com/refcardz/getting-started-application",
    "https://dzone.com/refcardz/getting-started-adobe-flash-0",
    "https://dzone.com/refcardz/getting-started-kanban",
    "https://dzone.com/refcardz/getting-started-nosql-and-data",
    "https://dzone.com/refcardz/jdbc-best-practices",
    "https://dzone.com/refcardz/getting-started-java-gui",
    "https://dzone.com/refcardz/getting-started-zend-framework",
    "https://dzone.com/refcardz/google-app-engine-java",
    "https://dzone.com/refcardz/agile-adoption-improving",
    "https://dzone.com/refcardz/getting-started-aspnet-mvc-10",
    "https://dzone.com/refcardz/getting-started-eclipse-rcp",
    "https://dzone.com/refcardz/getting-started-spring-dm",
    "https://dzone.com/refcardz/getting-started-db4o",
    "https://dzone.com/refcardz/enterprise-integration",
    "https://dzone.com/refcardz/seam-ui",
    "https://dzone.com/refcardz/core-mule",
    "https://dzone.com/refcardz/corecss3",
    "https://dzone.com/refcardz/essential-mysql",
    "https://dzone.com/refcardz/myeclipse",
    "https://dzone.com/refcardz/corecss-part1",
    "https://dzone.com/refcardz/glassfish-application-server",
    "https://dzone.com/refcardz/dependency-injection-in-ejb3",
    "https://dzone.com/refcardz/java-application-vulnerabilities",
    "https://dzone.com/refcardz/kubernetes-security-1",
    "https://dzone.com/refcardz/apache-cassandra",
    "https://dzone.com/refcardz/persistent-container-storage",
    "https://dzone.com/refcardz/understanding-data-quality",
    "https://dzone.com/refcardz/getting-started-vaadin",
    "https://dzone.com/refcardz/getting-started-lean-software",
    "https://dzone.com/refcardz/introduction-to-devops-analytics",
    "https://dzone.com/refcardz/nodejs",
    "https://dzone.com/refcardz/getting-started-with-etherium-private-blockchain",
    "https://dzone.com/refcardz/introduction-to-web-components-and-polymer",
    "https://dzone.com/refcardz/learn-microservices-in-java",
    "https://dzone.com/refcardz/getting-started-play-framework",
    "https://dzone.com/refcardz/continuous-testing-101",
    "https://dzone.com/refcardz/recommendations-using-redis",
    "https://dzone.com/refcardz/continuous-integration",
    "https://dzone.com/refcardz/restful-api-lifecycle-management",
    "https://dzone.com/refcardz/getting-started-cloud",
    "https://dzone.com/refcardz/continuous-integration-servers",
    "https://dzone.com/refcardz/getting-started-eclipse",
    "https://dzone.com/refcardz/getting-started-jboss",
    "https://dzone.com/refcardz/java-performance-optimization",
    "https://dzone.com/refcardz/getting-started-with-mqtt",
    "https://dzone.com/refcardz/getting-started-domain-driven",
    "https://dzone.com/refcardz/sql-syntax-for-apache-drill",
    "https://dzone.com/refcardz/javafx-8-1",
    "https://dzone.com/refcardz/monitoring-nginx",
    "https://dzone.com/refcardz/mobile-web-application-testing",
    "https://dzone.com/refcardz/mastering-portal-ui",
    "https://dzone.com/refcardz/html5-indexeddb",
    "https://dzone.com/refcardz/essential-postgis",
    "https://dzone.com/refcardz/html5-mobile-development",
    "https://dzone.com/refcardz/dns",
    "https://dzone.com/refcardz/couchbase-apis",
    "https://dzone.com/refcardz/http-hypertext-transfer-0",
    "https://dzone.com/refcardz/patterns-modular-architecture",
    "https://dzone.com/refcardz/java-profiling-visualvm",
    "https://dzone.com/refcardz/machine-learning-predictive",
    "https://dzone.com/refcardz/jetty",
    "https://dzone.com/refcardz/getting-started-apache-wicket",
    "https://dzone.com/refcardz/java-enterprise-edition-6-most",
    "https://dzone.com/refcardz/eclipselink-jpa",
    "https://dzone.com/refcardz/richfaces-40-next-generation",
    "https://dzone.com/refcardz/mvvm-design-pattern-formula",
    "https://dzone.com/refcardz/servicemix",
    "https://dzone.com/refcardz/developing-silverlight",
    "https://dzone.com/refcardz/functional-programming-clojure",
    "https://dzone.com/refcardz/getting-started-visual-studio",
    "https://dzone.com/refcardz/getting-started-uml",
    "https://dzone.com/refcardz/getting-started-firebug-15",
    "https://dzone.com/refcardz/getting-started-apache-ant",
    "https://dzone.com/refcardz/getting-started-fitnesse",
    "https://dzone.com/refcardz/getting-started-silverlight",
    "https://dzone.com/refcardz/getting-started-caucho-resin",
    "https://dzone.com/refcardz/getting-started-virtualization",
    "https://dzone.com/refcardz/getting-started-livecycle-data",
    "https://dzone.com/refcardz/getting-started-oracle",
    "https://dzone.com/refcardz/getting-started-grails",
    "https://dzone.com/refcardz/getting-started-javafx",
    "https://dzone.com/refcardz/bpm-bpmn",
    "https://dzone.com/refcardz/core-aspnet",
    "https://dzone.com/refcardz/soa-governance",
    "https://dzone.com/refcardz/equinox",
    "https://dzone.com/refcardz/essential-jsp-expression",
    "https://dzone.com/refcardz/junit-and-easymock",
    "https://dzone.com/refcardz/getting-started-with-jpa",
    "https://dzone.com/refcardz/very-first-steps-flex",
    "https://dzone.com/refcardz/intellij-idea",
    "https://dzone.com/refcardz/spring-configuration",
    "https://dzone.com/refcardz/responsive-web-design-8",
    "https://dzone.com/refcardz/angularjs-essentials",
    "https://dzone.com/refcardz/java-api-best-practices",
    "https://dzone.com/refcardz/data-warehousing",
    "https://dzone.com/refcardz/rest-foundations-restful",
    "https://dzone.com/refcardz/swift-essentials",
    "https://dzone.com/refcardz/blockchain-and-distributed-ledger-technology-for-d",
    "https://dzone.com/refcardz/improving-web-performance-with-varnish",
    "https://dzone.com/refcardz/essential-liferay-leading-open",
    "https://dzone.com/refcardz/devops-for-database",
    "https://dzone.com/refcardz/software-configuration",
    "https://dzone.com/refcardz/introduction-to-tensorflow",
    "https://dzone.com/refcardz/getting-started-with-spring-boot-and-microservices",
    "https://dzone.com/refcardz/getting-started-with-redis",
    "https://dzone.com/refcardz/declarative-pipeline-with-jenkins",
    "https://dzone.com/refcardz/getting-started-openstack-most",
    "https://dzone.com/refcardz/binary-repository-management",
    "https://dzone.com/refcardz/core-python",
    "https://dzone.com/refcardz/getting-started-java-ee",
    "https://dzone.com/refcardz/getting-started-infinispan",
    "https://dzone.com/refcardz/java-enterprise-edition-7",
    "https://dzone.com/refcardz/r-essentials-1",
    "https://dzone.com/refcardz/iot-applications-with-java-and-raspberry-pi",
    "https://dzone.com/refcardz/amqp-essentials",
    "https://dzone.com/refcardz/getting-started-with-industrial-internet",
    "https://dzone.com/refcardz/continuous-delivery-with-jenkins-workflow",
    "https://dzone.com/refcardz/getting-started-with-apache-tomcat",
    "https://dzone.com/refcardz/distributed-machine-learning",
    "https://dzone.com/refcardz/debugging-javascript",
    "https://dzone.com/refcardz/search-patterns",
    "https://dzone.com/refcardz/core-cpp",
    "https://dzone.com/refcardz/getting-started-subversion",
    "https://dzone.com/refcardz/sencha-touch",
    "https://dzone.com/refcardz/core-dart",
    "https://dzone.com/refcardz/mongodb",
    "https://dzone.com/refcardz/php-54-scalable",
    "https://dzone.com/refcardz/jenkins-paas",
    "https://dzone.com/refcardz/database-partitioning",
    "https://dzone.com/refcardz/html5-websocket",
    "https://dzone.com/refcardz/windows-powershell",
    "https://dzone.com/refcardz/chef-open-source-tool-scalable",
    "https://dzone.com/refcardz/coldfusion-builder-2-faster",
    "https://dzone.com/refcardz/netbeans-platform-70",
    "https://dzone.com/refcardz/cloud-computing-windows-azure",
    "https://dzone.com/refcardz/adonet-entity-framework-object",
    "https://dzone.com/refcardz/getting-started-selenium-20",
    "https://dzone.com/refcardz/getting-started-web-video",
    "https://dzone.com/refcardz/adobe-coldfusion-web-services-0",
    "https://dzone.com/refcardz/getting-started-windows-0",
    "https://dzone.com/refcardz/getting-started-griffon",
    "https://dzone.com/refcardz/leveraging-coldfusion-9",
    "https://dzone.com/refcardz/getting-started-repository",
    "https://dzone.com/refcardz/getting-started-adobe-flash",
    "https://dzone.com/refcardz/spring-web-flow",
    "https://dzone.com/refcardz/core-ws-bpel-business-process",
    "https://dzone.com/refcardz/getting-started-windows",
    "https://dzone.com/refcardz/getting-started-coldfusion-9",
    "https://dzone.com/refcardz/getting-started-drupal",
    "https://dzone.com/refcardz/apache-maven-2",
    "https://dzone.com/refcardz/birt",
    "https://dzone.com/refcardz/agile-adoption-decreasing-time",
    "https://dzone.com/refcardz/apache-tapestry-50",
    "https://dzone.com/refcardz/soa-patterns",
    "https://dzone.com/refcardz/core-seam",
    "https://dzone.com/refcardz/spring-annotations",
    "https://dzone.com/refcardz/javaserver-faces",
    "https://dzone.com/refcardz/netbeans",
    "https://dzone.com/refcardz/silverlight2",
    "https://dzone.com/refcardz/getting-started-ajax",
    "https://dzone.com/refcardz/continuous-delivery-patterns",
    "https://dzone.com/refcardz/temporal-data-processing",
    "https://dzone.com/refcardz/rest-api-security-1",
    "https://dzone.com/refcardz/cloud-capacity-management",
    "https://dzone.com/refcardz/agile-patterns",
    "https://dzone.com/refcardz/getting-started-apache-hadoop",
    "https://dzone.com/refcardz/apache-spark",
    "https://dzone.com/refcardz/docker-security",
    "https://dzone.com/refcardz/core-java-concurrency",
    "https://dzone.com/refcardz/scala",
    "https://dzone.com/refcardz/getting-started-with-memcached",
    "https://dzone.com/refcardz/nosql-and-data-scalability-20",
    "https://dzone.com/refcardz/getting-to-know-google-compute-engine-and-how-to-u",
    "https://dzone.com/refcardz/scalability",
    "https://dzone.com/refcardz/getting-started-git",
    "https://dzone.com/refcardz/reactive-programming-akka",
    "https://dzone.com/refcardz/scrum",
    "https://dzone.com/refcardz/contexts-and-depencency",
    "https://dzone.com/refcardz/essential-camel-components",
    "https://dzone.com/refcardz/getting-started-selenium",
    "https://dzone.com/refcardz/from-relational-to-graph-a-developers-guide",
    "https://dzone.com/refcardz/getting-started-with-apache-jmeter",
    "https://dzone.com/refcardz/coredotnet",
    "https://dzone.com/refcardz/getting-started-with-real-user-monitoring",
    "https://dzone.com/refcardz/functional-programming-with-javascript",
    "https://dzone.com/refcardz/intellij-idea-update",
    "https://dzone.com/refcardz/whats-new-php-55-56",
    "https://dzone.com/refcardz/spring-integration",
    "https://dzone.com/refcardz/css3",
    "https://dzone.com/refcardz/drools",
    "https://dzone.com/refcardz/core-spring-data",
    "https://dzone.com/refcardz/git-patterns-and-anti-patterns",
    "https://dzone.com/refcardz/object-oriented-javascript",
    "https://dzone.com/refcardz/essential-apache-http-server",
    "https://dzone.com/refcardz/deployment-automation-patterns",
    "https://dzone.com/refcardz/essential-mule-3-3",
    "https://dzone.com/refcardz/javafx-20-rich-client-platform",
    "https://dzone.com/refcardz/html5-canvas-web-standard",
    "https://dzone.com/refcardz/jquery-selectors",
    "https://dzone.com/refcardz/eclipse-tools-spring",
    "https://dzone.com/refcardz/adobe-flash-builder-45-develop",
    "https://dzone.com/refcardz/lucene",
    "https://dzone.com/refcardz/deploying-hadoop",
    "https://dzone.com/refcardz/designing-quality-software",
    "https://dzone.com/refcardz/phpunit-php-test-driven",
    "https://dzone.com/refcardz/solr-essentials",
    "https://dzone.com/refcardz/application-prototyping",
    "https://dzone.com/refcardz/objective-c-iphone-and-ipad",
    "https://dzone.com/refcardz/expression-based-authorization",
    "https://dzone.com/refcardz/flex-4-and-spring-3",
    "https://dzone.com/refcardz/getting-started-php-and-flex",
    "https://dzone.com/refcardz/getting-started-adobe",
    "https://dzone.com/refcardz/essential-f",
    "https://dzone.com/refcardz/getting-started-blazeds",
    "https://dzone.com/refcardz/eclipse-plug-development",
    "https://dzone.com/refcardz/core-html",
    "https://dzone.com/refcardz/javaserver-faces-20",
    "https://dzone.com/refcardz/agile-adoption-reducing-cost",
    "https://dzone.com/refcardz/flex-spring-integration",
    "https://dzone.com/refcardz/richfaces",
    "https://dzone.com/refcardz/essential-emf",
    "https://dzone.com/refcardz/using-xml-java",
    "https://dzone.com/refcardz/essential-ruby",
    "https://dzone.com/refcardz/corecss2",
    "https://dzone.com/refcardz/struts2",
    "https://dzone.com/refcardz/rss-and-atom",
    "https://dzone.com/refcardz/flexible-rails",
    "https://dzone.com/refcardz/gwt-style-configuration-and-js",
]

from tqdm import tqdm


item_list = []
for url in tqdm(card_url_list):
    try:
        doc = pq(url=url)

        number = doc("""span[class^="asset-number"]""").eq(0).text()
        title = doc("""h1[class="asset-title"]""").eq(0).text()
        subtitle = doc("""h2[class="subtitle"]""").eq(0).text()
        description = doc("""p[class="asset-description"]""").eq(0).text()
        download = doc("""dz-download""").eq(0).attr("asset").strip("'")

        item = {
            "number": number,
            "title": title,
            "subtitle": subtitle,
            "description": description,
            "download": download,
            "url": url
        }

        item_list.append(item)
        time.sleep(0.050)
    except Exception as e:
        print(url, e)

import json

json.dump(item_list, open("detail.json", 'w'))


"""
$('a[ng-href^="/refcardz"]').each(function ( index,element){ console.log(element.href)} );
$('span[class^="asset-number"]')[0].textContent
$('h1[class="asset-title"]')[0].textContent
$('h2[class="subtitle"]')[0].textContent
$('p[class="asset-description"]')[0].textContent
$('dz-download')[0].getAttribute('asset')

"""
